-- pgAdmin Database Setup Queries for CollabSphere

-- Note: Run these queries in order after creating an empty database in pgAdmin.
-- This matches the schema generated by Flask-SQLAlchemy in models.py

-- 1. Create the 'users' table
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(120) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    interests VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc')
);

-- 2. Create the 'rooms' table
CREATE TABLE rooms (
    id SERIAL PRIMARY KEY,
    subject VARCHAR(100) NOT NULL,
    creator_id INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    CONSTRAINT fk_rooms_creator_id FOREIGN KEY (creator_id) 
        REFERENCES users (id) ON DELETE CASCADE
);

-- ==========================================
-- Troubleshooting & Deployment Tips
-- ==========================================
-- 1. If deploying to platforms like Heroku or Render:
--    You'll need to set the `DATABASE_URL` environment variable to your PostgreSQL connection string.
--    Example: postgresql://username:password@hostname:5432/databasename
--
-- 2. SQLAlchemy `db.create_all()` Behavior:
--    Even if you run these manually in pgAdmin, leaving `db.create_all()` in `app.py` is perfectly safe. 
--    SQLAlchemy checks if the tables exist and simply won't overwrite them if they do.
--    However, for a production environment, you should transition to using `Flask-Migrate` (Alembic) 
--    instead of `db.create_all()` to manage schema changes over time securely.
